---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "post.fullname" . }}
  labels:
    app: reddit
    component: post
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: reddit
    component: post
    release: {{ .Release.Name }}
