apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "post.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "post.fullname" . }}
            port:
              number: 5000
