---
- hosts: all
  become: yes
  tasks:
    - name: Ensure old versions of Docker are not installed.
      package:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - containerd.io
          - runc
          - docker-ce-cli
        state: absent
