---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mongo.fullname" . }}
  labels:
    app: reddit
    component: mongo
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: mongo
      release: {{ .Release.Name }}
  template:
    metadata:
      name: mongo
      labels:
        app: reddit
        component: mongo
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mongo
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: mongo
          protocol: TCP
        env:
        - name: mongo_DATABASE_HOST
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
